
CREATE DATABASE DATABASE_UCB

USE DATABASE_UCB

CREATE TABLE PERSONA(
ID			INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
NOMBRE		VARCHAR(100) NOT NULL,
CARNET		VARCHAR(8) NOT NULL,
EDAD		VARCHAR(4) NOT NULL,
SEXO		VARCHAR(10) NOT NULL,

);

INSERT INTO PERSONA (NOMBRE, CARNET, EDAD, SEXO)
VALUES('MARCELO', 111213, 20, 'MASCULINO')




CREATE TABLE PERSONAL_CENSO(
ID						INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
NOMBRE					VARCHAR(100) NOT NULL,
);



INSERT INTO PERSONAL_CENSO (NOMBRE)
VALUES('MARTIN')



CREATE TABLE INFORMACION_RECOPILADA(
ID					INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
CARNET				VARCHAR(4) NOT NULL,
DOMICILIO			VARCHAR(100) NOT NULL,
CANTIDAD_FAMILIARES VARCHAR(4) NOT NULL,
)


INSERT INTO INFORMACION_RECOPILADA(CARNET, DOMICILIO, CANTIDAD_FAMILIARES)
VALUES (111312,'AV. Moscu, 5to anillo, Estacion Moragrande', 4)


SELECT * FROM PERSONA
SELECT * FROM PERSONAL_CENSO
SELECT * FROM INFORMACION_RECOPILADA